### ISSUE TITLE
[HotFix] Throw unknown type when positional type load from other file

### ISSUE THREAD

**Issue by HairyRabbit** [HearTao/ts-cli#4]
```ts
import { E } from "./enum"

export default function(foo: E) { foo; }
```

```
> ts-cli-export-from-other-file@ start d:\Workspace\ts-cli\test\export-from-other-file
> ts-node -e "require('ts-cli').default('./index.ts', {})"

(node:11224) UnhandledPromiseRejectionWarning: Error: Unsupports positional type "import("d:/Workspace/ts-cli/test/export-from-other-file/enum").E"
    at makeUnsupportsTypeError (d:\Workspace\ts-cli\src\transformer.ts:347:10)
    at makeCommandTypeExpression (d:\Workspace\ts-cli\src\transformer.ts:216:14)
    at d:\Workspace\ts-cli\src\transformer.ts:189:11
    at Array.map (<anonymous>)
    at makeCommandProperties (d:\Workspace\ts-cli\src\transformer.ts:187:17)
    at makeCommandPositionals (d:\Workspace\ts-cli\src\transformer.ts:180:10)
    at Object.transformCommand (d:\Workspace\ts-cli\src\transformer.ts:136:23)
    at Object.generate [as default] (d:\Workspace\ts-cli\src\generator.ts:18:18)
    at Object.<anonymous> (d:\Workspace\ts-cli\src\index.ts:16:11)
    at step (d:\Workspace\ts-cli\dist\node_modules\tslib\tslib.js:136:27)
```

![image](https://user-images.githubusercontent.com/5752902/62513345-51274a00-b84e-11e9-81b1-8206d89fd466.png)

**Comment by HairyRabbit** [comment]
`isEnum()` failed when the enum have only one member, the type was `EnumMember` not `EnumDeclaration` should use `isEnumLiteral()`

**Comment by HairyRabbit** [comment]
The positional option should not contain **type** field, when use "choices" together
